### ISSUE TITLE
Please review and merge these changes

### ISSUE THREAD

**Issue by tetsuo55** [timduru/platform-frameworks-base#10]
Cherry picks for timduru

https://github.com/UBERROMS/frameworks_base/commit/681f901411cc0eed1ecf48a230cb4d8a001c4472
https://github.com/UBERROMS/frameworks_base/commit/3a3fbf2eb9af93bfab819470c3f87b2c7177e323
https://github.com/UBERROMS/frameworks_base/commit/22bc07a1a8fb1e7d5389c719d26dfbae07da0ab8
https://github.com/UBERROMS/frameworks_base/commit/e60ddf25f9ccb0acc23b90afae6a8bd9642c61d5
https://github.com/UBERROMS/frameworks_base/commit/e3b2caef44fe4c268c9e38cac8ffbd214c91494c
https://github.com/UBERROMS/frameworks_base/commit/5ba94241f60cdfe80b39aa1f28b3a9fe45b776e4
https://github.com/UBERROMS/frameworks_base/commit/2cfea0eabc6483cff6a1b2b9ea8d9b99b31f2374
https://github.com/UBERROMS/frameworks_base/commit/1e0772c5265cceac7df5e8f0472a1f295f3dcac5
https://github.com/UBERROMS/frameworks_base/commit/4df140a85730aae888da160bdd348073f6e89448
https://github.com/UBERROMS/frameworks_base/commit/cdf59c5d1ba96d9badeb45dff5ea612649cbcc61
https://github.com/UBERROMS/frameworks_base/commit/1677ed21c0996ad9b41d0dbcc09edf60d2f69d09
https://github.com/UBERROMS/frameworks_base/commit/87eed1225fe625964cf057cd74b6ff7262786be6
https://github.com/UBERROMS/frameworks_base/commit/b37f3499715d7237b9a325da0d247e3a19d5760c
https://github.com/UBERROMS/frameworks_base/commit/da2e4a18059ccaa62e3d9e2bf1170944b820a933
https://github.com/UBERROMS/frameworks_base/commit/cb9b5cfaf487a259c8460879f830f40e91e42a54
https://github.com/UBERROMS/frameworks_base/commit/a7242cf705cd28730ee2170a2e23b8a3a66af9cb
https://github.com/UBERROMS/frameworks_base/commit/e37a9ef4e3f0b791abf40aa257bca04753c8e661
https://github.com/UBERROMS/frameworks_base/commit/66be5aabbd2d6340e663260f6df079b2bb5ea557
https://github.com/UBERROMS/frameworks_base/commit/4663d7af2e3b88498e2f68d20f2a5e8767aec8e6
https://github.com/UBERROMS/frameworks_base/commit/935aabde925095df5e89175dc7b9d9f2ce7bb118
https://github.com/UBERROMS/frameworks_base/commit/61619c94746d3907ba2ac2cef9ca32d5195f1e33
https://github.com/UBERROMS/frameworks_base/commit/1266eb7e5a8ecc90bd155abb4eaa9006588c3d8f
https://github.com/UBERROMS/frameworks_base/commit/ccc09d2d4c474cc04789f10caaafac2c4a10b514
https://github.com/UBERROMS/frameworks_base/commit/52630de8e1483ec8255dd6eccc753adba0376275
https://github.com/UBERROMS/frameworks_base/commit/6138a9942d9e4bf20318f41687e72a6b8292f743
https://github.com/UBERROMS/frameworks_base/commit/7922cd4728547ab1b7d9a273abe730eb3abf688f
https://github.com/UBERROMS/frameworks_base/commit/05adc78ebc5c828cfb55e41847b77c0d63de5b5e
https://github.com/UBERROMS/frameworks_base/commit/3ec0d470891da12570bc4d1b40e07cf02761a40c
https://github.com/UBERROMS/frameworks_base/commit/182760ac3cc232d8d27231e54cdf7cec25767111
https://github.com/UBERROMS/frameworks_base/commit/0bf8b50a149dc9730eff5538c4f48aba9a4b71c3
https://github.com/UBERROMS/frameworks_base/commit/e563d77cd526736a8fd45c2c338b00f82440ec05
https://github.com/UBERROMS/frameworks_base/commit/d447a35ad4a36c1c688f9cb711d2dbddc8483336
https://github.com/UBERROMS/frameworks_base/commit/11380848a2b74fc7e90c44627e48544cb4224a3a
https://github.com/UBERROMS/frameworks_base/commit/f5fdeb32c57e6daced286dc486b38af9d49fce37
https://github.com/UBERROMS/frameworks_base/commit/d4a4f1b5f6f20429915b1f40dcb403c16c40de7a
https://github.com/UBERROMS/frameworks_base/commit/68e12912f728e7e1fd0a45f40535177406b94c01
https://github.com/UBERROMS/frameworks_base/commit/c7b84c115b9e696fcce0422e438912251e55f8e8
https://github.com/UBERROMS/frameworks_base/commit/51e374ea6dbd686510a33f1a59c8ad14028f1a94
https://github.com/UBERROMS/frameworks_base/commit/bfd0c53e3442f77ddec76f47bc48532a713e19b8
https://github.com/UBERROMS/frameworks_base/commit/50a0cc015a06c3a817025d081a4b45eed97a523c
https://github.com/UBERROMS/frameworks_base/commit/29c45dc3c6745b5586b7c2b605b118b661fa1148
https://github.com/UBERROMS/frameworks_base/commit/efb6f6ca2fd97b5ef667043b926a8e316aeb7dba
https://github.com/UBERROMS/frameworks_base/commit/9baa64f1037d75b5656f43ebd075bdb93d2b851a
https://github.com/UBERROMS/frameworks_base/commit/99085c6e4b64c56ebce8797298c909df31d61069
https://github.com/UBERROMS/frameworks_base/commit/9d8d87f3450abc0d2290cda92f60e9ceaaaaf928
https://github.com/UBERROMS/frameworks_base/commit/4cd090d31d95e32dd39f0ffe4467247364c15ac5
https://github.com/UBERROMS/frameworks_base/commit/da5078a218429d476dd1ece149b95591c5db1b2e
https://github.com/UBERROMS/frameworks_base/commit/a2ad42649e8f312bac0197cc6e5aca0be7626bb8
https://github.com/UBERROMS/frameworks_base/commit/3748b198ba8521555187cfd553f6ab7e60aa5040
https://github.com/UBERROMS/frameworks_base/commit/5af795c22028560819ab6fbb4a02c0b5a060a011
https://github.com/UBERROMS/frameworks_base/commit/55973e466cca3bbbfba161fb9899d6cf80ed0c5f
https://github.com/UBERROMS/frameworks_base/commit/4f76ccaec95a30757308feb3530cfb6762a7bb2f
https://github.com/UBERROMS/frameworks_base/commit/c9c132c02d7e4cc254fdcba93ebcfd845811e021
https://github.com/UBERROMS/frameworks_base/commit/62bc8cb7f8898281f18deae1c79cf349eeb583f9
https://github.com/UBERROMS/frameworks_base/commit/2e28a76965be61b0b5db422553a3360962e5422c
https://github.com/UBERROMS/frameworks_base/commit/5e00dbbcdf0a5f1d20f8edad0db5f869747b560b
https://github.com/UBERROMS/frameworks_base/commit/5eadc55f7fe18c2dba7edaa32cf002bb808d1f02
https://github.com/UBERROMS/frameworks_base/commit/6d878db8d7559c5edf45451d592dc7a14860d705
https://github.com/UBERROMS/frameworks_base/commit/536e5eb00a906354414bc569cdc77c39d7ecf304
https://github.com/UBERROMS/frameworks_base/commit/997066418994c8897e371b70c95c8845001c6280
https://github.com/UBERROMS/frameworks_base/commit/4e3cc23c4641750c8722fb10be2c56178690c7b3
https://github.com/UBERROMS/frameworks_base/commit/661809085b66c2c6d9c205f5c48394028973e443
https://github.com/UBERROMS/frameworks_base/commit/7e853a4fea250bdfcd4b79b52db2ac3dcc23d8d4
https://github.com/UBERROMS/frameworks_base/commit/3e73858e14f2c051c0c09355dc9b6fde74a0c007
https://github.com/UBERROMS/frameworks_base/commit/438febafdc4323bec808b95f7addcca7c10f3e77
https://github.com/UBERROMS/frameworks_base/commit/7e17713973968c32b9ee4e8949315e8fe38ddcb5
https://github.com/UBERROMS/frameworks_base/commit/a00601c9ac5b837f26bc30d7cdcdbce1899366cb
https://github.com/UBERROMS/frameworks_base/commit/e879761e192bfd5ca2113a8212b09f729ec043dd
https://github.com/UBERROMS/frameworks_base/commit/dc6e12fceed92f3dac9107fc1591f7b88a1db273
https://github.com/UBERROMS/frameworks_base/commit/5ccf2560cbc25505922d496da69f63d3e1ab6a16
https://github.com/UBERROMS/frameworks_base/commit/c0b5f7d6f0c569e5ebce273672f43d84bfb775b8
https://github.com/UBERROMS/frameworks_base/commit/27182015865c101b039ad275f35a182651992df1
https://github.com/UBERROMS/frameworks_base/commit/ba17f970e2e2c935627e7aaf3d6f9fac76535e74
https://github.com/UBERROMS/frameworks_base/commit/971cf702a2730df40d02dcc463030a2f015876e3
https://github.com/UBERROMS/frameworks_base/commit/ea676d064e2fe2d7f1ffe053a58df67e58f3dc4f
https://github.com/UBERROMS/frameworks_base/commit/6d9a0f1a52f2b9b87f983b60fe508211879d7f13
https://github.com/UBERROMS/frameworks_base/commit/8ba6ace46622c70f4d5f16855470805d01020c51
https://github.com/UBERROMS/frameworks_base/commit/7011e650c26855bb1713be30bb929dd62049aef0
https://github.com/UBERROMS/frameworks_base/commit/256092266a46082762ab58a085987f1849d6b497
https://github.com/UBERROMS/frameworks_base/commit/8654d925a7439e345bb182a070928bb2ecc59327
https://github.com/UBERROMS/frameworks_base/commit/47fcc0f8ed0b1b8fa0edcb0b5f23020222063952
https://github.com/UBERROMS/frameworks_base/commit/d6dbbce7cd7067f4bb50c456f3932504965d61f7
https://github.com/UBERROMS/frameworks_base/commit/d10f777741630b8da19d248f0ead498781b98712
https://github.com/UBERROMS/frameworks_base/commit/7a86dbc3d6361518a60b9659ab2f5048a97af07b
https://github.com/UBERROMS/frameworks_base/commit/f2987c05a5892a1041aa8a6a1943c59e5ee14f8e
https://github.com/UBERROMS/frameworks_base/commit/d055c2bdcda6af6ec1dd69155e35d4834fb64bdc
https://github.com/UBERROMS/frameworks_base/commit/9463e646c198ca86b6bd69ebc905171d221a6d21
https://github.com/UBERROMS/frameworks_base/commit/aa914b8f021bdb3ed883ba0ae2215bcd5fc71231
https://github.com/UBERROMS/frameworks_base/commit/f5fbc3607e3b018d043ad4dbdf5bbd729d636ace
https://github.com/UBERROMS/frameworks_base/commit/88781106235fd7c8b6b376d0a01d43711310e536
https://github.com/UBERROMS/frameworks_base/commit/546cd66e7cc8b1e3cc05b0b6020458b83bffe1a2
https://github.com/UBERROMS/frameworks_base/commit/c319ce924b101a7e679046fea3abb40f9adbcfaa
https://github.com/UBERROMS/frameworks_base/commit/f51eb8900fe46721ffa1e556c9d9de63dd217514
https://github.com/UBERROMS/frameworks_base/commit/56dcc521117785517cb39ddb65132abb38bbd1fb
https://github.com/UBERROMS/frameworks_base/commit/63dc53424f28f510c5a7d76e5ac802827418ccda
https://github.com/UBERROMS/frameworks_base/commit/a03960c6972740f12abf57d5c51328f275f17a00
https://github.com/UBERROMS/frameworks_base/commit/1c5007a51dc6ba311b28f38e75081fdbb8e19cc8
https://github.com/UBERROMS/frameworks_base/commit/d579915c8e0f54f649fde4556b0659db5e63cb83
https://github.com/UBERROMS/frameworks_base/commit/02fe25efaf56d8c555c1c51abcc32783378b70a6
https://github.com/UBERROMS/frameworks_base/commit/10fcc7e9b008957cebe33f8943d00b2730e28d4d
https://github.com/UBERROMS/frameworks_base/commit/ab78e42ce631ab2244b52484087fa097c555e02a
https://github.com/UBERROMS/frameworks_base/commit/8bf213ff6fa3460c0a4065d34570edf456e3963d
https://github.com/UBERROMS/frameworks_base/commit/bb0d00cccf468cdcc477d58cd8a43124e2b0807d
https://github.com/UBERROMS/frameworks_base/commit/fd2b544c98d47e272330e754b272b443dcfccc93
https://github.com/UBERROMS/frameworks_base/commit/f9511f375d2a1789daabac3c4f1982fe3d6c8eff
https://github.com/UBERROMS/frameworks_base/commit/dbd2ef0c9c5ae7c378f5b47ea076b4ea2033c477
https://github.com/UBERROMS/frameworks_base/commit/f1dab078f5986d4444ab01c80b14707048e1598c
https://github.com/UBERROMS/frameworks_base/commit/d6dc893050b9a5e4fbba6b60804d6406145e7500
https://github.com/UBERROMS/frameworks_base/commit/a81e9d73a088a585796833c03a3b07da0d7144a4
https://github.com/UBERROMS/frameworks_base/commit/2cccfea1ee36bbabefe7f2af466d31954377aa52
https://github.com/UBERROMS/frameworks_base/commit/7b7b84dec14d39c6aee51aa0517041354d1d6d1e
https://github.com/UBERROMS/frameworks_base/commit/70fd05f7e9dd6a4134bb7f18dcc1e432a23922e2
https://github.com/UBERROMS/frameworks_base/commit/e48d2d7de4003d8196fe596a4f90fb08a35eaaef
https://github.com/UBERROMS/frameworks_base/commit/57083d3f5dec67fa41d857f996420f1a6db73a2c
https://github.com/UBERROMS/frameworks_base/commit/a33929aa14f8b26576825171691cf26e74feca1f
https://github.com/UBERROMS/frameworks_base/commit/9ee8de6a8d8c2e366e7b99bbfacdf0d4194f043d
https://github.com/UBERROMS/frameworks_base/commit/83b99bca935d6ae9fc6b289f66a02a2ae0e1c8c7
https://github.com/UBERROMS/frameworks_base/commit/380a2ba13968894b292aed034904d4dcfc9b5b69
https://github.com/UBERROMS/frameworks_base/commit/bba6dfd8fe37768a2e032fabed9e88f16a1b6456
https://github.com/UBERROMS/frameworks_base/commit/cd1de68b76cd2616ff876b67607d91f11472a8d7
https://github.com/UBERROMS/frameworks_base/commit/319fedfef12043ca534f4972c41c8d1a507d768e
https://github.com/UBERROMS/frameworks_base/commit/27d6390b061c4bb75445cf4d6b7fe02f41702e6c
https://github.com/UBERROMS/frameworks_base/commit/8320dd224f94afa116d86a2269f46ff3ac960479
https://github.com/UBERROMS/frameworks_base/commit/5be0e33a6774bf29545e511156335a99b8ca7d34
https://github.com/UBERROMS/frameworks_base/commit/1564d35321ae4413a981daeedead4785ee3f75d8
https://github.com/UBERROMS/frameworks_base/commit/c5e8db9749c0f6dd0ab5fb91478ba00c32e4e415
https://github.com/UBERROMS/frameworks_base/commit/7ad1c505189e327cb13a0f3f3939db0fa2623ac4
https://github.com/UBERROMS/frameworks_base/commit/17e5692dbbd5a3673ba8657ac413a5a85204318b
https://github.com/UBERROMS/frameworks_base/commit/81f56ef4c0ccc68a1957cd2955b4c2b92e34cfd6
https://github.com/UBERROMS/frameworks_base/commit/a19db53fab954d08ce724fd9e8e933a6a4fa1b18
https://github.com/UBERROMS/frameworks_base/commit/d7d21cd1bf8631f800672c46d847aaf7552f2035
https://github.com/UBERROMS/frameworks_base/commit/8f748d4f74cb23d247d5231373dbc712ee65224b
https://github.com/UBERROMS/frameworks_base/commit/e7c9b4db9dc2d32b55159b427a2efd5c06d50215
https://github.com/UBERROMS/frameworks_base/commit/5fb1146bd556a80f24c232089a2533292fd3ee2f
https://github.com/UBERROMS/frameworks_base/commit/1ae2ee9ca8f66c9e45db4464d1931bc2befa87c7
https://github.com/UBERROMS/frameworks_base/commit/a3be41a52f385d49287efabd57dbfda8f37207f3
https://github.com/UBERROMS/frameworks_base/commit/bb98bce9bfa2f6286d0066a7787685574a4d81b5
https://github.com/UBERROMS/frameworks_base/commit/aaa821161a0f397380494c6429849699a8e473b8
https://github.com/UBERROMS/frameworks_base/commit/0ad514d5b132cf9f6b8bb510c7144e74b4a4c625
https://github.com/UBERROMS/frameworks_base/commit/c59d0344b69b595ed1ae8f733e5f221fde647b35
https://github.com/UBERROMS/frameworks_base/commit/dff4dfabe0d7a2f40786e9fb59fd34cece239a52
https://github.com/UBERROMS/frameworks_base/commit/8ef7968aa93857e93c0cfbd40a313545afdcd602
https://github.com/UBERROMS/frameworks_base/commit/d2218e2888690d0b7b105b255ced88a6e4e589be
https://github.com/UBERROMS/frameworks_base/commit/066e9ef561bd57bf70b349b4570072c2c08506b1
https://github.com/UBERROMS/frameworks_base/commit/83b4f2b675dd5e2df51a4978097d602917c96d03
https://github.com/UBERROMS/frameworks_base/commit/0eb5b6597df149a905616a38bdc498382e6b5431
https://github.com/UBERROMS/frameworks_base/commit/0bb5542d21a3ce12fcf2bbe8d4e77549013e454b
https://github.com/UBERROMS/frameworks_base/commit/42c2192329f52b3d174ab16e94dbf3eb352f4adb
https://github.com/UBERROMS/frameworks_base/commit/cd6899b6394fe8985bae6f4f629230669d7950b1
https://github.com/UBERROMS/frameworks_base/commit/86a254c5acbe961d12fe9077acf108d4da027219
https://github.com/UBERROMS/frameworks_base/commit/5b8871bf315d5e183ad8404082830a76ba064f80
https://github.com/UBERROMS/frameworks_base/commit/20a4ffd1e56999211aaee960f8132a9867d5378a
https://github.com/UBERROMS/frameworks_base/commit/c12c08df0ef54e8e2a8d4b7bec101e689c77bbaa
https://github.com/UBERROMS/frameworks_base/commit/83737da00d5966ff16827806cf6483af1de981a1
https://github.com/UBERROMS/frameworks_base/commit/07e702a107b09a7bc2002ef21c7d735437531242
https://github.com/UBERROMS/frameworks_base/commit/c33ee3cedd9d771c8a8891cf4f27a30c55842b8f
https://github.com/UBERROMS/frameworks_base/commit/d17dd7676b45efd7c6c3fcfa5cad5e09ef4bb8ba
https://github.com/UBERROMS/frameworks_base/commit/1f72d9e1f9800cd3250565b12e9ce6794f6515d7
https://github.com/UBERROMS/frameworks_base/commit/1280cbd0c361c115da88455ffb09386d6d1bd0d5
https://github.com/UBERROMS/frameworks_base/commit/9c94e680ea0e3262ef17ee33b472227cbbb888f7
https://github.com/UBERROMS/frameworks_base/commit/1187c4704d3c2409049e9a917ab3184fe8ab31d3
https://github.com/UBERROMS/frameworks_base/commit/2f0e53bf0e716fbd9f915f7c4410ac2965671297
https://github.com/UBERROMS/frameworks_base/commit/da327623b3c8514bcb74df5066bfbb73d0c8f19c
https://github.com/UBERROMS/frameworks_base/commit/bbdede0b7b5c1e09b0bdcc94c6738a31f9f07dfe
https://github.com/UBERROMS/frameworks_base/commit/274d496c174e53e4651d3ff1f692944c873402d0
https://github.com/UBERROMS/frameworks_base/commit/4312d8c6b461eccb5fbe6d101fb32e1d004832d0
https://github.com/UBERROMS/frameworks_base/commit/2bf3d1e7fcec0f5bf5335ab96b1b745f7c998392
https://github.com/UBERROMS/frameworks_base/commit/ea9c46f73bc336fd22e65d9b17798fba6b87fa38
https://github.com/UBERROMS/frameworks_base/commit/570f2d0c7255020c42c62767c191eefd588cdeab
https://github.com/UBERROMS/frameworks_base/commit/7f603c5b380f31cc2c05243d698cdc2395c58a79
https://github.com/UBERROMS/frameworks_base/commit/8b33d1d7cdfbac70f9f1dc58b105edb8b9d6125c
https://github.com/UBERROMS/frameworks_base/commit/3c04ce1f664dc9bc02acc8ecbdda39df45610f67
https://github.com/UBERROMS/frameworks_base/commit/e1f7f083a4fb4ef8165171e9f2d971481d714613
https://github.com/UBERROMS/frameworks_base/commit/6a26f34f506325f0150976341635350cfcf290e4
https://github.com/UBERROMS/frameworks_base/commit/26eff2007b26544a161c9f156ce3f3d5f7268ad2
https://github.com/UBERROMS/frameworks_base/commit/209bba791b72af7cacfedfaeccaf1f8deafd7400
https://github.com/UBERROMS/frameworks_base/commit/3683c3a19247253279370105bfda5f0f487cc8d1
https://github.com/UBERROMS/frameworks_base/commit/2770e12a5281662f3fead8a60751833ea88422b8
https://github.com/UBERROMS/frameworks_base/commit/b5cce0f55dfd6b4d107f4a6cc10be05874a40e1f
https://github.com/UBERROMS/frameworks_base/commit/828196c147c3f86a64f255c13d62798a6018dbd6
https://github.com/UBERROMS/frameworks_base/commit/eb971b467739734de7ca1fa006e305e5c5d441c5
https://github.com/UBERROMS/frameworks_base/commit/9ca45337e5a6c64b6236cdf0ea959bac5c678443
https://github.com/UBERROMS/frameworks_base/commit/61813348800182579bada665fab68f05ef973f45
https://github.com/UBERROMS/frameworks_base/commit/071e26c4afe160c2cf1ba33168fe5334dedeeda6
https://github.com/UBERROMS/frameworks_base/commit/07eb4a0a970c0721c884af9baba89af14057558a
https://github.com/UBERROMS/frameworks_base/commit/dd91d28f2ca0eebd4af991d56f4bf7bd7726c5ea
https://github.com/UBERROMS/frameworks_base/commit/ca5574e0f03451692354e0da5030eceb5c5442b5
https://github.com/UBERROMS/frameworks_base/commit/8b45de09d65c0a5067f8481e6139a96d8fb805d3
https://github.com/UBERROMS/frameworks_base/commit/fbf517192bee1205105b54aa3d3e5c535fba0fc0
https://github.com/UBERROMS/frameworks_base/commit/f7f73845f6f54491af1f60461865f5326d10a024
https://github.com/UBERROMS/frameworks_base/commit/9d3c931abf790469c950ad9da47254c30123542e
https://github.com/UBERROMS/frameworks_base/commit/97ecedbca7f1bbe4b9d206bdac3217a2076c153e
https://github.com/UBERROMS/frameworks_base/commit/5c42b7c1fd44dc1a72627f99cfe5dc905ecb1f2a
https://github.com/UBERROMS/frameworks_base/commit/b6beae63ccb4950d6d028e5de1a80c5873c8e058
https://github.com/UBERROMS/frameworks_base/commit/e81dcf67f20f60b78256f5cff47255b129f81f72
https://github.com/UBERROMS/frameworks_base/commit/37019adc71f345cf29218b2fb295bd08685d8107
https://github.com/UBERROMS/frameworks_base/commit/c68d9d7a42f780bd867b2a302107876c8aa82673
https://github.com/UBERROMS/frameworks_base/commit/985557da1b05ba732282a126178811643a852165
https://github.com/UBERROMS/frameworks_base/commit/f3d6ed82fece1c1791f4a3f30df21ccd4d292348
https://github.com/UBERROMS/frameworks_base/commit/621fc29a3ced8f96f09d3de622cfa433bc5c2f50

**Comment by timduru** [comment]
okie, thanks.
merged a few of these
